AllCops:
  TargetRubyVersion: 2.6
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
