version: '3'

services:
  web:
    build:
      context: ../discrepancies_service
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "tail -f /dev/null"
    volumes:
      - .:/discrepancies_service
    stdin_open: true
    tty: true
